name: Build aports

on:
  workflow_dispatch:
  push:
    branches:
      - main
  schedule:
    # Every day at 3am
    - cron: "0 3 * * *"

concurrency: buildrepo

jobs:
  alpine-image:
    runs-on: ubuntu-latest
    outputs:
      digest: ${{ steps.image-info.outputs.digest }}
    steps:
      - name: Checkout tidylabs/aports
        uses: actions/checkout@v4

      - name: Get Alpine image digest
        id: image-info
        run: |
          IMAGE=$( \
            grep -Eo -m 1 \
              -e "alpine(:[0-9][.0-9]*)(@sha256:[0-9A-Za-z]+)?" \
              .devcontainer/Dockerfile \
          )
          docker pull "${IMAGE}"
          docker inspect --format="digest={{index .RepoDigests 0}}" "${IMAGE}" >> "$GITHUB_OUTPUT"

  buildrepo:
    runs-on: ubuntu-latest
    needs: alpine-image
    container:
      image: ${{ needs.alpine-image.outputs.digest }}
    environment: release
    permissions:
      contents: write
    env:
      PACKAGER: alpine-dev@tidylabs.net
      USE_CCACHE: 1
    steps:
      - name: Get Alpine version
        id: alpine-release
        run: |
          ALPINE_RELEASE="$(cat /etc/alpine-release)"
          echo version_minor="${ALPINE_RELEASE}" >> "$GITHUB_OUTPUT"
          echo version_major="${ALPINE_RELEASE%.*}" >> "$GITHUB_OUTPUT"

      - name: Install build dependencies
        run: apk add --update alpine-sdk ccache doas python3 rclone tar

      - name: Configure git user
        uses: tidylabs/action-git-config-user@v2

      - name: Checkout alpinelinux/aports
        uses: actions/checkout@v4
        with:
          repository: alpinelinux/aports
          ref: v${{ steps.alpine-release.outputs.version_minor }}
          path: alpinelinux-aports

      - name: Checkout tidylabs/aports
        uses: actions/checkout@v4
        with:
          path: tidylabs-aports

      - name: Configure rclone
        run: |
          RCLONE_CONFIG="$HOME/.config/rclone/rclone.conf"
          mkdir -p "${RCLONE_CONFIG%/*}"
          echo "${{ secrets.RCLONE_CONFIG }}" > "${RCLONE_CONFIG}"

      - name: Restore build cache
        uses: actions/cache@v4
        with:
          path: |
            /var/cache/apk
            /var/cache/distfiles
            ~/.cache
          key: aports-${{ steps.alpine-release.outputs.version_minor }}-${{ github.run_id }}
          restore-keys: |
            aports-${{ steps.alpine-release.outputs.version_minor }}
            aports-${{ steps.alpine-release.outputs.version_major }}

      - name: Download packages
        run: |
          rclone mkdir -v remote:v${VERSION_MAJOR}/
          rclone sync -v remote:v${VERSION_MAJOR}/ ~/packages/
        env:
          VERSION_MAJOR: ${{ steps.alpine-release.outputs.version_major }}

      - name: Setup signing keys
        run: |
          MODULUS_HASH=$( \
            echo "${{ secrets.PACKAGER_PRIVKEY }}" \
            | openssl rsa -modulus -noout \
            | cut -d "=" -f2 \
            | openssl md5 \
            | awk '{print substr($2,0,8)}' \
          )
          PACKAGER_PRIVKEY="${HOME}/.abuild/${PACKAGER}-${MODULUS_HASH}.rsa"
          mkdir -p "${PACKAGER_PRIVKEY%/*}"
          echo "${{ secrets.PACKAGER_PRIVKEY }}" > "${PACKAGER_PRIVKEY}"
          echo "PACKAGER_PRIVKEY=${PACKAGER_PRIVKEY}" >> "${HOME}/.abuild/abuild.conf"

          PACKAGER_PUBKEY="/etc/apk/keys/$(basename ${PACKAGER_PRIVKEY}).pub"
          mkdir -p "${PACKAGER_PUBKEY%/*}"
          openssl rsa -in "${PACKAGER_PRIVKEY}" -pubout -out "${PACKAGER_PUBKEY}"
          echo "PACKAGER_PUBKEY=${PACKAGER_PUBKEY}" >> "${HOME}/.abuild/abuild.conf"

      - name: Configure ccache
        run: |
          mkdir -p "${HOME}/.ccache"
          cp tidylabs-aports/ccache.conf "${HOME}/.ccache/."
          ccache \
            -o base_dir="${GITHUB_WORKSPACE}" \
            -o remote_storage="${{ secrets.CCACHE_REMOTE_STORAGE }}"
          ccache -p

      - name: Build aarch64 cross compiler
        run: tidylabs-aports/scripts/bootstrap-cc.sh aarch64
        env:
          APORTSDIR: alpinelinux-aports

      - name: Build 'community' repo (x86_64)
        run: tidylabs-aports/scripts/buildrepo.py tidylabs-aports/community

      - name: Build 'community' repo (aarch64)
        run: tidylabs-aports/scripts/buildrepo.py tidylabs-aports/community
        env:
          CHOST: aarch64
          EXTRADEPENDS_TARGET: libgcc libstdc++ musl-dev

      - name: Upload packages
        run: rclone sync -v ~/packages/ remote:v${VERSION_MAJOR}/
        env:
          VERSION_MAJOR: ${{ steps.alpine-release.outputs.version_major }}

      - name: Flatten packages
        run: |
          REPODIR=~/packages
          for path in $(find "$REPODIR" -type f); do
            relpath="${path#$REPODIR/}"
            flatpath="$REPODIR/${relpath//\//+}"
            mv "$path" "$flatpath"
          done

      - name: Publish release w/ packages
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ steps.alpine-release.outputs.version_major }}
          target_commitish: ${{ github.sha }}
          fail_on_unmatched_files: true
          files: /github/home/packages/*